spring.application.name=trackpot
# ========== SERVER & LOGGING ==========
server.port=8080
logging.level.org.springframework=INFO

# ========== JPA / HIBERNATE ==========
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# ========== DATASOURCE (driver only) ==========
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== FLYWAY (optional) ==========
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ========== OTHER COMMONS ==========
# e.g. timezone
spring.jackson.time-zone=UTC

# ========== ACTUATOR ==========
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=true
